"""Initial migration.

Revision ID: e8b42c77075d
Revises: 
Create Date: 2024-10-03 00:37:09.120428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b42c77075d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('journal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'journals', ['journal_id'], ['id'])

    with op.batch_alter_table('paper_authors', schema=None) as batch_op:
        batch_op.drop_constraint('paper_authors_author_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('paper_authors_paper_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'author', ['author_id'], ['id'])
        batch_op.create_foreign_key(None, 'paper', ['paper_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper_authors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('paper_authors_paper_id_fkey', 'paper', ['paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('paper_authors_author_id_fkey', 'author', ['author_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('journal_id')

    # ### end Alembic commands ###
